name: PR Notification to Discord

on:
  pull_request:
    types: [opened, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "New Pull Request created: ${{ github.event.pull_request.html_url }} by ${{ github.event.pull_request.user.login }}"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
